

name: Manual workflow


on:
  workflow_dispatch:
    
    #inputs:
     # name:
       
      #  description: 'Person to greet'
        
       # default: 'World'
     
        #required: false

  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Codebase
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # role-to-assume: arn:aws:iam::779527285137:role/AWSdevopscerttaskrole
         aws-region: us-east-1

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.2'
          
      - name: terraform init
        run: terraform init --input=false

      - name: terraform format
        run: terraform fmt -check

      - name: terraform validate
        run: terraform validate
              # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks

    #  - name: terraform scan
     #   uses: accurics/terrascan-action@main
      #  with:
       #   iac_type: 'terraform'
       
      - name: terraform plan
        run: terraform plan
       
      - name: terraform apply
        run: terraform apply -auto-approve
        
      - name: terraform destroy
        run: terraform destroy    
        
